### ISSUE TITLE
Trained Helsinki no-bottom model

### ISSUE THREAD

**Issue by omarsamiranov** [chenzhaiyu/points2poly#16]
Hello,
I would like to run the current approach on a custom dataset. My dataset of buildings contain no bottoms for the buildings. You mentioned in the paper that for the real world Shenzhen dataset you used  Helsinki no-bottom model. Can you please provide the trained model?

Also I expect that I will use it the same way as provided in the readme. Just adding the model url and name in the config file, am I correct?

**Comment by chenzhaiyu** [comment]
Hi @omarsamiranov, one [no-bottom model](https://1drv.ms/f/s!AseUjD457t0Sg6MGc7M1_0JEJrUXOA?e=fwa4CA) I have just at hand for a follow-up work has been trained on airborne LiDAR. Otherwise, you can easily train one with the provided [Helsinki data](https://1drv.ms/f/s!AseUjD457t0Sgtptq5PZlrPBwu8N_A?e=mvtSrw). Please always mind the gap between the training data and your custom dataset, and retrain it if possible.

The only difference I reckon at the moment when using a no-bottom model is to set `append_bottom` to `true`: 
https://github.com/chenzhaiyu/points2poly/blob/f194e87524c08a539378e5186433966f021e3cf3/conf/config.yaml#L23
