### ISSUE TITLE
Can't product result

### ISSUE THREAD

**Issue by fangxunyes** [chenzhaiyu/points2poly#7]
Hi, I'm learning your method but I have some question, can I get any tips?
this is my environment
![1667569735103](https://user-images.githubusercontent.com/109592560/199988457-a643a79e-9799-4627-b845-f1150b2c2b77.jpg)
(1)
I download helsinki_mini datasets and helsinki_fullview_model，and I run reconstructed.py to get six *obj building though it reports some warnings.
![1667572842758](https://user-images.githubusercontent.com/109592560/200002656-7425fc3f-fa05-4925-b58c-251ea3f1d447.jpg)
[reconstruct.log](https://github.com/chenzhaiyu/points2poly/files/9938968/reconstruct.log)
but I can't get result when I run evaluate.py
![2 (1)](https://user-images.githubusercontent.com/109592560/199995330-8da380a7-88d6-4394-b58b-2ee0842f9511.jpg)
![2 (2)](https://user-images.githubusercontent.com/109592560/199995362-ff03137e-26df-4fea-b9db-c3c5115dc3e0.jpg)
(2)
I try to make building models from my point cloud.
I reconstruct a 3D model of a district using UAV and I extract the building by terrasolid. The cavities are caused by trees. this is my input building in mapple. 
![1667571632683](https://user-images.githubusercontent.com/109592560/199997834-e22307fb-40c7-49b7-a418-c6572e27dcdc.jpg)
this is the RANSAC result.(all default)
![1667571753960](https://user-images.githubusercontent.com/109592560/199998493-d66d87dc-2ba8-4a65-9b95-5ae54d9b37b7.jpg)
I follow the step in readme.md to product my datasets and I run reconstruct.py. It seems running but I can't get the ‘reconstructed’ folder.
I only change the dataset name in config
![1667573092494](https://user-images.githubusercontent.com/109592560/200003487-3993ebb8-cbcc-4490-84e6-a328b6a53418.jpg)
[reconstruct2.log](https://github.com/chenzhaiyu/points2poly/files/9939327/reconstruct2.log)

**Comment by chenzhaiyu** [comment]
Hi @fangxunyes, thanks for bringing so many details into the issue. I cloned the repo into a fresh env and performed the steps you mentioned - unfortunately I coudn't reproduce what you encountered: 

1. I was able to get the evaluation result as a CSV file. Please make sure `{dir_reconstructed}` points to the original dir where the reconstructed buildings are saved, instead of the new dir automatically generated from subsequent runs. Try to look through every subfolder in `./outputs` (The automatically generated logging dir is confusion - I'll try to fix it :).
2.  From the last screenshot you posted, it's clear that `number of extracted cells: 0` resulted in `no reacheable cells. aborting`. This could result from several reasons:
    * Your point cloud doesn't capture the building bottom, therefore make sure to append the bottom plane to the cell complex by changing this configuration to `true`:
    https://github.com/chenzhaiyu/points2poly/blob/d5589a4d736e79efb3803340987dad6803da7d84/conf/config.yaml#L23
    * and therefore you actually cannot directly use the provided model weights which were trained on fullview buildings (including bottom view). Consider training your own model.
    * The RANSAC result looks super colorful/messy, which means you might have extracted too many trivial planar segments. Maybe adjust the RANSAC parameters (e.g., increase the number of minimal supporting points per segment), such that you only end up with the principal and meaniful ones. This I guess isn't the main reason, just a side note.
